participants:
  - cl_type: lighthouse
    cl_image: sigp/lighthouse:v8.0.0-rc.0
    el_type: geth
    el_image: ethereum/client-go:v1.16.4
    supernode: true
  - cl_type: teku
    cl_image: consensys/teku:25.9.3
    el_type: reth
    el_image: ghcr.io/paradigmxyz/reth:v1.8.1
    supernode: true
  - cl_type: grandine
    cl_image: sifrai/grandine:2.0.0.rc0
    el_type: nethermind
    el_image: nethermindeth/nethermind:release-1.34.0
    supernode: true
  - cl_type: prysm
    cl_image: gcr.io/offchainlabs/prysm/beacon-chain:v6.1.1
    el_type: besu
    el_image: hyperledger/besu:25.9.0
    supernode: true
  - cl_type: lodestar
    cl_image: chainsafe/lodestar:v1.35.0-rc.0
    el_type: besu
    el_image: hyperledger/besu:25.9.0
  - cl_type: nimbus
    cl_image: statusim/nimbus-eth2:multiarch-v25.9.2
    el_type: geth
    el_image: ethereum/client-go:v1.16.4
network_params:
  fulu_fork_epoch: 1
  bpo_1_epoch: 2
  bpo_1_max_blobs: 15
  bpo_1_target_blobs: 10
  bpo_2_epoch: 3
  bpo_2_max_blobs: 21
  bpo_2_target_blobs: 14
additional_services:
  - dora
  - blockscout
  - spamoor